[project]
name = "comfyui-yuan"
description = "Some simple&practical ComfyUI image processing nodes."
version = "1.0.0"
license = {file = "LICENSE"}
dependencies = ["opencv-python"]

[project.urls]
Repository = "https://github.com/Cyber-BlackCat/ComfyUI-Yuan"
#  Used by Comfy Registry https://comfyregistry.org

[tool.comfy]
PublisherId = "cyber-blackcat"
DisplayName = "ComfyUI-Yuan"
Icon = ""
